//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYPER_SYSTEM.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        public int MaDonHang { get; set; }
        public Nullable<int> MaDichVu { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
    
        public virtual DICHVU DICHVU { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
