//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYPER_SYSTEM.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class NAPTIEN
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int MaNapTien { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
